sudo: required

services:
  - postgresql

addons:
  postgresql: 9.5

language: php

php:
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

before_script:
  - psql -c 'CREATE DATABASE pdo_test;' -U postgres
  - psql -U postgres pdo_test < ./Tests/TestCase/schema.sql

script:
  - ./vendor/bin/tester -o console -p php Tests/
  - ./vendor/bin/parallel-lint -e php,phpt Core Tests
  - ./vendor/bin/phpstan analyse -l max -c phpstan.neon Core/
  - ./vendor/bin/phpcs --standard=ruleset.xml --extensions=php,phpt --encoding=utf-8 --tab-width=4 -sp Core/

after_failure:
  - for i in $(find Tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done