sudo: required

services:
  - postgresql

addons:
  postgresql: 9.5

language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

before_script:
  - psql -c 'CREATE DATABASE test_database;' -U postgres
  - psql -U postgres test_database < ./Tests/Config/schema.sql

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then ./vendor/bin/phing ci; else ./vendor/bin/phing all-tests; fi

after_failure:
  - for i in $(find Tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
